### ISSUE TITLE
Which file does lexicon_file refer to?

### ISSUE THREAD

**Issue by superwars** [ttthy/ure#2]
Following "readme", I got train.txt, dev.txt, test.txt, dict.entity, dict.enttype, dict.ent_wf, dict.relation, dict.word. However, I don't know which one is the lexicon_file in the next step? 

Specifically, my problem is in the following step:

We also provide the file for feature extraction
python ure/preprocessing/feature_extractor.py --input_file [file] --lexicon_file [file] --output_file [file] --threshold [occurrence threshold]

Thanks!

**Comment by ttthy** [comment]
Hi @superwars , 

I updated README.
Please use the following command for generating the lexicon_file:
```bash
python ure/preprocessing/feature_extractor.py --generate_lexicon --input_file [file] --lexicon_file [file] --output_file [file] --threshold [occurrence threshold]
```

Let me know if you have any other questions.

**Comment by henuykc** [comment]
> problem

Hello, brother, I want to run this code, but I don't know how to make the data of train.txt/tese.txt/dev.txt in the correct format. The data set of TACRED I downloaded is only train.json/test.json/dev.json. Can you tell me how to generate train.txt/test.txt/dev.txt in the correct format? Thank you!
