### ISSUE TITLE
How to generate dict.features ?

### ISSUE THREAD

**Issue by ChunhuaLiu596** [ttthy/ure#4]
Hi Thy Thy, 

Thanks for sharing this code! 

I'm trying to the the March model. But got the error of `data/nyt/dict.features' not exist. Could you share more details about how it generated? 

Besides, may I double-check the feature generation process with you?  Following the README.md, I used the following commands to generate with *.lexicon and *.features for train/dev/test respectively. 

> python ure/preprocessing/feature_extractor.py --generate_lexicon --input_file data/nyt/train.txt --lexicon_file data/nyt/train.lexicon --output_file data/nyt/train.features --threshold 1

> python ure/preprocessing/feature_extractor.py --generate_lexicon --input_file data/nyt/dev.txt.filtered --lexicon_file data/nyt/dev.lexicon --output_file data/nyt/dev.features --threshold 1

> python ure/preprocessing/feature_extractor.py --generate_lexicon --input_file data/nyt/test.txt.filtered --lexicon_file data/nyt/test.lexicon --output_file data/nyt/test.features --threshold 1` 

> python ure/preprocessing/feature_extractor.py --input_file data/nyt/train.txt --lexicon_file data/nyt/train.lexicon --output_file data/nyt/train.features --threshold 1

> python ure/preprocessing/feature_extractor.py --input_file data/nyt/dev.txt.filtered --lexicon_file data/nyt/dev.lexicon --output_file data/nyt/dev.features --threshold 1

> python ure/preprocessing/feature_extractor.py --input_file data/nyt/test.txt.filtered --lexicon_file data/nyt/test.lexicon --output_file data/nyt/test.features --threshold 1

Is it the same process as you did? 

Please let me if I missed something. 

Much appreciated for your help!

**Comment by henuykc** [comment]
Hello, brother, have you solved this problem? I also want to run this code, but I don't know how to make the data of train.txt/tese.txt/dev.txt in the correct format. I think the issue you mentioned seems to have these data. Can you tell me how it is made? thank you!
