### ISSUE TITLE
I can't run EType's code

### ISSUE THREAD

**Issue by henuykc** [ttthy/ure#5]
Hi,
    I'm writing a paper related to URE. I want to use your paper EType as a comparison algorithm. But I can't run your code on GitHub right now. I tried to run the code according to the relevant tips of README, but I was very confused about the processing of data sets. I couldn't find a way to generate "nyt/train.txt (or tacred/ train.txt)" and other data files. Therefore, could you please send a more detailed operation instruction or complete data after NYT and TACRED processing? Thank you very very much!

**Comment by ttthy** [comment]
Hi @henuykc ,

First of all, thanks for your interest in our paper. 
Regarding the data format, we have provided the sample file here [data/sample.txt](https://github.com/ttthy/ure/blob/master/data/sample.txt) and also mentioned in the README: 

- For NYT: you can contact Diego Marcheggiani for the full data
- TACRED: We use Stanford CoreNLP to obtain dependency features for TACRED. You can transfer the original json to the required format by writing your own preprocessing script.
